### ISSUE TITLE
NullPointerException on Startup in Thread "Timer-1"

### ISSUE THREAD

**Issue by danielghrist** [UTSA-CS-3443/Delivery-Service#5]
I receive the following error on both my M2 Mackbook Air and my really old Windows 10 Desktop PC when the program first opens:

"Exception in thread "Timer-1" java.lang.NullPointerException
	at application.controller.Controller.setCursor(Controller.java:54)
	at application.controller.MainController$2.run(MainController.java:192)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)"

I believe this is a bug with one of the timer threads that control the opening animation. It also will not show the menu options if I just let the opening animation play out, it will only show if I click the "Show Options" button, even after the animation has finished.

**Comment by danielghrist** [comment]
Corrected issue by removing the setCursor Timer as that seemed to be the problem Thread and just set the cursor in the Main.java upon switching scenes like the other controllers had been doing.
